### ISSUE TITLE
browser.test_pthread_malloc_free regression

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#4380]
This test broke due to f8e0b7dc838dea8b713944b5c9469be837826999. After that commit, we fail to build the source file for that test, on `error: use of undeclared identifier 'EAGAIN'`.

@cynecx, I think the change might be due to the include reordering you did in that commit?

Very possibly the test is wrong and missing an include, but we should check and fix.

**Comment by cynecx** [comment]
I will look into this tomorrow. :)

**Comment by juj** [comment]
Noticed this also, it's fixed in pull request #4372. (missing include)

**Comment by juj** [comment]
Merged that pull request, so this should now be fixed in incoming.
