### ISSUE TITLE
browser.test_cocos2d_hello fails

### ISSUE THREAD

**Issue by kripken** [kripken/emscripten#5659]
cc @caiiiycuk 

````
test_cocos2d_hello (test_browser.browser) ... 
(process:9443): GLib-CRITICAL **: g_slice_set_config: assertion 'sys_page_size == 0' failed
INFO:root:generating port: libCocos2d.bc... (this will be cached in "/home/alon/.emscripten_cache/asmjs/libCocos2d.bc" for subsequent builds)
INFO:root:building port: Cocos2d v3
WARNING:root:Cocos2d: library is experimental, do not expect that it will work out of the box
Traceback (most recent call last):
  File "emcc", line 13, in <module>
    emcc.run()
  File "emcc.py", line 1320, in run
    compile_source_file(i, input_file)
  File "emcc.py", line 1309, in compile_source_file
    args = get_bitcode_args([input_file]) + ['-emit-llvm', '-c', '-o', output_file]
  File "emcc.py", line 1292, in get_bitcode_args
    args = system_libs.process_args(args, shared.Settings)
  File "tools/system_libs.py", line 726, in process_args
    args = port.process_args(Ports, args, settings, shared)
  File "tools/ports/cocos2d.py", line 75, in process_args
    get(ports, settings, shared)
  File "tools/ports/cocos2d.py", line 62, in get
    return [shared.Cache.get('libCocos2d', create, what='port')]
  File "tools/cache.py", line 100, in get
    temp = creator()
  File "tools/ports/cocos2d.py", line 25, in create
    os.path.join(ports.get_build_dir(), 'Cocos2d', 'samples'))
  File "/usr/lib/python2.7/shutil.py", line 177, in copytree
    os.makedirs(dst)
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/home/alon/.emscripten_cache/asmjs/ports-builds/Cocos2d/samples'
FAIL
[Browser harness server terminated]
````
Working around the mkdir failure, it hits some other failures I don't understand. So something strange has happened here.

**Comment by caiiiycuk** [comment]
Hi Alon! I faced the same problem inside my project. Currently I don't know why it is happen but EM_ASM wan't works as expected.
Inside CCEGLView.cpp there is EM_ASM block:
```
        var getMousePos = function(event) {
            var rect = Module["canvas"].getBoundingClientRect();
            var cw = Module["canvas"].width;
            var ch = Module["canvas"].height;
            var scrollX = ((typeof window.scrollX !== 'undefined') ? window.scrollX : window.pageXOffset);
            var scrollY = ((typeof window.scrollY !== 'undefined') ? window.scrollY : window.pageYOffset);
            
            var x = event.pageX - (scrollX + rect.left);
            var y = event.pageY - (scrollY + rect.top);

            x = x * (cw / rect.width);
            y = y * (ch / rect.height);
            return [x, y];
        };
...
```

Compiler fails on ```return [x, y]; ```. In my project compiler files on var defenitions inside EM_ASM block, like this:
```
var a,b;
```

If I split this definitions into two line, all works.

Now I try to build test case and bisect.

**Comment by caiiiycuk** [comment]
Ok, simple test does not work:
```
#include <emscripten.h>

int main(int argc, char** argv) {
  EM_ASM({
    var a,b;
  });
  return 0;
}
```
Errors:
```
asm-bug.cpp:5:11: error: use of undeclared identifier 'b'
    var a,b;
          ^
asm-bug.cpp:4:3: error: expected unqualified-id
  EM_ASM({
  ^
/home/caiiiycuk/emscripten/sdk/emscripten/system/include/emscripten/em_asm.h:47:79: note: expanded from macro 'EM_ASM'
#define EM_ASM(code, ...) ((void)emscripten_asm_const_int(#code, ##__VA_ARGS__))
                                                                              ^
asm-bug.cpp:7:3: error: expected unqualified-id
  return 0;
  ^
asm-bug.cpp:8:1: error: extraneous closing brace ('}')
}
```

Maybe I miss understand how EM_ASM should works. Trying bisect.

**Comment by caiiiycuk** [comment]
3b2cd86c725c0908e869dd3a67bd61bad92f3c72 is the first bad commit
commit 3b2cd86c725c0908e869dd3a67bd61bad92f3c72
Author: Jukka Jylänki <jujjyl@gmail.com>
Date:   Sat Aug 26 13:35:34 2017 +0300

    Improve testing of EM_ASM code blocks, and handling of inputs that would have become non-evaluating strings in the body of an ASM_CONST. Revise the core set of EM_ASM functions to be EM_ASM_VOID, EM_ASM_INT and EM_ASM_DOUBLE, as well as EM_ASM which is a convenient alias to EM_ASM_INT. Deprecate EM_ASM_, EM_ASM_ARGS, EM_ASM_INT_V and EM_ASM_DOUBLE_V as redundant. This closes #5480.

:100644 100644 b2f9ab8fe8e1a09868eb59d8c398221c9adcb011 c8cdef313a9dde104c188a8027cee6b23c504f80 M  emscripten.py
:040000 040000 71ae6a4eaeb4129ec849ad1a345ffa68704886aa b1345285f0be9b631a2f339090c3b8040e6b6c76 M  system
:040000 040000 89ba34888f7e27c9d0c3967f6707b295e36a5a07 b8f6c64208151885a7ea9835609ab72c1b98cfc0 M  tests

**Comment by caiiiycuk** [comment]
cc @juj 
I'am not sure that I use EM_ASM corretly, so need explanation, to understand what to do. Maybe I should fix cocos2d sources.

**Comment by kripken** [comment]
Thanks for investigating. Yeah, it looks like breakage from @juj's recent EM_ASM changes, which is worrying.

**Comment by juj** [comment]
Very sorry about this - this is the issue with `EM_ASM` params now being interpreted as input parameters. See https://github.com/kripken/emscripten/commit/3b2cd86c725c0908e869dd3a67bd61bad92f3c72#commitcomment-24703774 for explanation, and https://github.com/kripken/emscripten/commit/d1edecf4908cd05d765094c3863114d94931e173#diff-7455103ae92b1d16e3655e8e1aded632R43 for the updated documentation.

Effectively, to fix the issue, change

```
  EM_ASM({
    var a,b;
  });
```

to

```
  EM_ASM((
    var a,b;
  ));
```

@caiiiycuk : does that work?

**Comment by kripken** [comment]
@juj: Side note, this breaking change has perhaps not gotten enough attention, perhaps we should mention it on the mailing list?

**Comment by juj** [comment]
Good point, let me throw an email about this.

**Comment by SaschaNaz** [comment]
This can be closed now, right?

**Comment by caiiiycuk** [comment]
I think so.

**Comment by trss** [comment]
How would we make the example work with the `-std=c99` option?

**Comment by caiiiycuk** [comment]
Sorry, what do you mean? When you set this -std=c99 what errors do you have?

**Comment by trss** [comment]
Command (test.c contains the code with the fix, which works without `-std=c99`):
```
emcc -std=c99 test.c
```
Result:
```
test.c:4:3: error: expected expression
  EM_ASM((
  ^
/usr/local/Cellar/emscripten/1.37.40/libexec/system/include/emscripten/em_asm.h:153:95: note: expanded from macro 'EM_ASM'
#define EM_ASM(code, ...) ((void)emscripten_asm_const_int(#code _EM_ASM_PREP_ARGS(__VA_ARGS__)))
                                                                                              ^
1 error generated.
ERROR:root:compiler frontend failed to generate LLVM bitcode, halting
```

**Comment by trss** [comment]
Used `-std=gnu99` instead and stuff works again.
