### ISSUE TITLE
emsdk install failing

### ISSUE THREAD

**Issue by Krelborn** [kripken/emscripten#6275]
I am trying to update my emsdk installation and getting the following error after running `./emsdk install latest`.

```
Installing tool 'emscripten-1.37.34'..
Error downloading URL 'https://github.com/kripken/emscripten/archive/1.37.34.tar.gz': <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
Installation failed!
```

I'm seeing this whether I try to upgrade an existing installation or install from a clean copy of the SDK. Platform is macOS. I tried to install 1.37.33 as well and that failed with the same error. Is anyone else seeing this problem?

**Comment by frittblas** [comment]
Yes I have the same problem but with emscripten-1.37.35
Error downloading..
I'm on windows.

**Comment by jjyyxx** [comment]
Similar problem. 
Platform: windows
`Error downloading URL 'https://github.com/kripken/emscripten/archive/1.37.35.zip': <urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>`

However, i was able to download the archive manually from the browser. Is there a way to bypass the download stage(maybe put the archive to a specific directory manually) and install directly?

**Comment by LMLB** [comment]
@jjyyxx Put the zip in the `zips` folder and make sure it has the same file name as in the URL (i.e. `1.37.35.zip`, not `emscripten-1.37.35.zip`). Then run the install command again and it will detect that the zip file is already downloaded.

**Comment by Krelborn** [comment]
That's a good workaround, thanks!

**Comment by jjyyxx** [comment]
Thanks. It works perfectly

**Comment by LMLB** [comment]
This seems to have been caused by https://github.com/blog/2507-weak-cryptographic-standards-removed. The version of Python included in the Windows build is too old.

**Comment by kripken** [comment]
Sounds like we need to update the Python in the windows emsdk, but is this windows-only? The initial report here was on Mac.

**Comment by Krelborn** [comment]
Yep I’m seeing this on macOS 10.12 and 10.13.

**Comment by kripken** [comment]
Is the core issue the same, do those MacOS versions ship with too-old versions of python?

**Comment by Krelborn** [comment]
Python version is 2.7.10 on both macOS versions I've tried, I guess that must be too old if that's the issue.

**Comment by mapsam** [comment]
Just updated to MacOS 10.13.3 and the install latest command worked! 

Adding some things I saw, which may or may not be helpful. `tlsv1 alert protocol version` error searches reveal mostly python and openssl issues. I noticed before the MacOS upgrade I was running openssl `0.9.8` but now I'm running `LibreSSL 2.2.7`.

**Comment by frittblas** [comment]
kripken - yes it's an issue on windows too. I also got this error when trying to compile a project that worked fine in 1.35.00

urllib2.URLError: <urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>

**Comment by LMLB** [comment]
Sorry, I missed that it was originally reported on macOS, as I had the same issue on Windows.

It's actually the version of OpenSSL that's too old (version 1.0.1 or higher is needed for TLS 1.2). Python 2.7.5 for Windows includes OpenSSL 0.9.8y, and macOS 10.13.3 includes OpenSSL 0.9.8zh.

**Comment by Krelborn** [comment]
Yep, I've retried on macOS 10.13 and it does seem to work so it's just 10.12 where I have the problem (Which is my main development machine). I'll use the workaround that was posted until I get round to upgrading. Thanks for the responses!

**Comment by juj** [comment]
I'm able to reproduce this on Windows.

Thanks for troubleshooting versions in the above, very useful. Emsdk bundles the [Portable Python](http://portablepython.com/wiki/Download/) package on Windows, and on other OSes depends on python being installed by default on the system.

Unfortunately latest version of Portable Python seems to be 2.7.6.1, which by @Krelborn 's comment above seems to be too old, as 2.7.10 was detected to be too old. It looks like we need to source an up to date portable python installation.

**Comment by juj** [comment]
https://winpython.github.io/ looks promising, I'll see if we could migrate to using that.

Although https://stackoverflow.com/questions/29472289/is-there-portable-python-2-7-windows-distribution-without-any-libraries-included suggests "I have to unpack 1.5GB first and uninstall unused packages." so not sure if this might cause a download size impact.

**Comment by LMLB** [comment]
FYI: According to the release notes on python.org, Python 2.7.7 on Windows includes OpenSSL 1.0.1g.

Note that the version of Python shouldn't matter on macOS, as it is only on Windows that Python has its own copy of OpenSSL baked in. On other operating systems Python relies on the OpenSSL version that is installed in the system.

**Comment by juj** [comment]
A fix is now in https://github.com/juj/emsdk/commit/4c8ea1b10be7ab59ec0bb5a63934372cb4c2bcff

It would be great if someone can help trying this out:

```
git clone https://github.com/juj/emsdk.git
cd emsdk
emsdk install latest
emsdk activate latest
```

should obtain Python 2.7.13.1 64-bit and Emscripten 1.37.35 precompiled.

**Comment by juj** [comment]
On macOS side, I'm thinking that we have no other easy option rather to call macOS 10.12 unsupported, and ask users to update to macOS 10.13? Or I wonder if manually downloading and replacing macOS bundled python with a newer python via homebrew or similar would work?

**Comment by mischnic** [comment]
Installing binaryen (#6276) works with Python 2 and 3 from Homebrew:
```bash
$ python2 --version
Python 2.7.14
$ python3 --version
Python 3.6.4
$ python2 /usr/local/bin/emcc -s WASM=1 main.c #works
$ python3 /usr/local/bin/emcc -s WASM=1 main.c #works
```

More permanent solution (bash):
```bash
alias emcc="python2 /usr/local/bin/emcc" # or python3
```

**Comment by ypoissant** [comment]
I am trying to add SIMD support to our application and I get the following error:
error: Linking globals named 'emscripten_float64x2_add': symbol multiply defined!
This error is reviewed in bug #5867 so I tried to follow the instructions, that is installing the latest but the installation fails with the error:
Error downloading URL 'https://github.com/kripken/emscripten/archive/1.37.35.zip': <urlopen error [Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>
I also tried to install the 1.37.23 (as per instruction in #5867) but got the same error.
I know this is due to an old Python version in the sdk distribution but I'm not experienced enough with the sdk to do a manual install. I'm stuck with 1.37.22.
Is there a fix in the pipeline for this?

**Comment by kripken** [comment]
Has anyone had a chance to try @juj's steps a few comments back? https://github.com/kripken/emscripten/issues/6275#issuecomment-368590913 I think we're waiting on that to move forward here.

**Comment by ratkingsminion** [comment]
@juj's steps worked, but I had to get Python first, so "should obtain Python" wasn't true

**Comment by nicebyte** [comment]
@kripken it worked for me, though the first couple of times "emsdk update" failed with:

```
env.bat
'env.bat' is not recognized as an internal or external command,
```

however, it somehow magically fixed itself on third try.

**Comment by kripken** [comment]
Thanks @ratkingsminion and @nicebyte!

I opened #6298 to update the docs regarding that. It seems safest to tell people to get python themselves for now based on the feedback here, until we figure out bundling python for windows (see also #6288). The PR also mentions the proper MacOS version etc.

**Comment by e99majo** [comment]
I cannot install on mac oc x 10.13.1

`Error downloading URL 'https://github.com/kripken/emscripten/archive/1.37.35.tar.gz': <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version  (_ssl.c:661) `

`Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 12:01:12) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin`

I cannot help but notice that I succeeds in downloading from aws, but failes from github. The workaround makes me able to install, but later on when compiling where zlib is used, it fails in downloading that.

**Comment by e99majo** [comment]
Turns out I had gotten two version of python2 installed will trying to resolve this and emsdk was picking up the wrong one. Managed to uninstall the "wrong" one, (2.7.14) which i got from python.org and now running 2.7.10. The one from python.org has Openssl 0.9.8zh. The mac os bundled version of python has LibreSSL 2.2.7

**Comment by LMLB** [comment]
The one that has OpenSSL 0.9.8zh does not come with OpenSSL included, it uses the system-supplied OpenSSL library (which Apple deprecated in Mac OS X 10.7).

Python 3.6 is the first release to include its own private copy of OpenSSL (1.0.2) on macOS. Older Python releases, including all versions of Python 2.7, use the deprecated system-supplied OpenSSL library.

**Comment by AndresCuervo** [comment]
@juj I wouldn't recommend saying 10.12 is unsupported as I can confirm that running `brew install python2` per @mischnic's comment above resolved this issue on MacOS `10.12.6`. Maybe the resolution is that this should be added to the [Platform Specific Notes](https://github.com/juj/emsdk#platform-specific-notes) section?

**Comment by kripken** [comment]
@AndresCuervo the [current docs](https://github.com/kripken/emscripten/commit/3f51bacbd0fc7c9e7a16aa8438fdd3246979f1e8#diff-8070aedc10b79456e2e300d0269ca0cfR63) suggest 10.13 but that you can install newer python manually. Does it look clear enough to you there? Perhaps we should mention brew directly?

**Comment by AndresCuervo** [comment]
Ah yeah I think my confusion came from `brew upgrade python` automatically
offering to migrate to python3. It wasn't until I ran `brew upgrade
python2` that I realized my mistake, so I think specifying `brew upgrade
python{2,3}` would be best (I'm unsure if that bash-ism will work with
brew).

**Comment by kripken** [comment]
Sounds good. Is the python3 version in brew new enough like the python2 one to avoid the ssl bug, so we can recommend either? (or should we just recommend 2?)

**Comment by kimown** [comment]
```
Installing SDK 'sdk-1.37.36-64bit'..
Installing tool 'clang-e1.37.36-64bit'..
The contents of file 'llvm/tag/osx_64bit/emscripten-llvm-e1.37.36.tar.gz' already exist in destination '/Users/google/com/mdk/emsdk/clang/e1.37.36_64bit', skipping.
Done installing tool 'clang-e1.37.36-64bit'.
Installing tool 'node-8.9.1-64bit'..
The contents of file 'node-v8.9.1-darwin-x64.tar.gz' already exist in destination '/Users/google/com/mdk/emsdk/node/8.9.1_64bit', skipping.
Done installing tool 'node-8.9.1-64bit'.
Installing tool 'emscripten-1.37.36'..
Error downloading URL 'https://github.com/kripken/emscripten/archive/1.37.36.tar.gz': <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
Installation failed!

```

still mistake.

**Comment by kripken** [comment]
@kimown which os and version of python are you using? we recently updated the docs to mention that newer python is required as discussed in this issue.

**Comment by zsavicreative** [comment]
I can confirm that on windows 10 pro the python included in the emsdk-portable download was failing for me, after removing the python contents, I just replaced it with my own python 2.7 root and left the folder name as is, managed to download/install without issues.

**Comment by bzz** [comment]
Updating to 1.37.36 (and installing python2 as a workaround for #5418) solved the issue on macOS 10.12 for me.

Thank you!

**Comment by juj** [comment]
Emsdk updated to using Python 2.7.13.1 on Windows since this bug was originally reported, so it should be fixing the issue on Windows, although the problem is that if user has old Python on emsdk on Windows, they cannot use `emsdk update` + `emsdk install latest` to update to the newest version, since the updater relies on being able to download with Python, so in such scenario, manually bootstrapping to the latest version should be done by redownloading the portable installer (which has the updated Python 2.7.13.1 in it).

It's good to know that on macOS manually updating Python e.g. via brew will help. Unlike Windows, on macOS we don't bundle Python in emsdk because macOS comes with Python shipped, and we've been assuming that it would be a functional one.

I'll close this bug as fixed - unfortunately a manual update of Python or redownload of emsdk may be needed for users, but once one has the latest version, the issue should not be present.

**Comment by kripken** [comment]
>  manually bootstrapping to the latest version should be done by redownloading the portable installer (which has the updated Python 2.7.13.1 in it).

Note that we currently do not link to an installer for windows, instead [we recommend people get the emsdk and let it do the rest](https://kripken.github.io/emscripten-site/docs/getting_started/downloads.html), like on other platforms. (Because I don't know how to build or test the installer...)

**Comment by marswong** [comment]
installing `1.37.36` on macOS `10.13.4` with python `2.7.14` still failed.

**Comment by damu** [comment]
Seems like emsdk is still using Python 2.7.5.3 and that it still has this issue. I just tried it today and installed Python 3.6.5 before because emsdk wouldn't even start otherwise. See https://github.com/juj/emsdk/issues/140
@juj

**Comment by juj** [comment]
> Note that we currently do not link to an installer for windows

The NSIS installer .exes on Windows were deprecated at some point, since it was not much gain to support an extra deployment workflow, and the Windows emsdk portable zip based package does much of the same thing with less hassle. The only thing that's different in the Windows emsdk portable zip package compared to macOS and Linux is that in the Windows package, we [bundle portable Python 2.7.13.1](https://github.com/juj/emslave/blob/master/bin/deploy_emsdk.py#L144) into the zip package.

**Comment by juj** [comment]
Oh hmm, I now see that the Downloads page at http://kripken.github.io/emscripten-site/docs/getting_started/downloads.html# no longer mentions a link to the downloadable zip packages. That is, to these zip files:
 - Windows: https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.zip
 - Linux and OS X: https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz

and indeed, in the above, `emsdk-portable.zip` still has old Python. I think we need to make the S3 bots roll out a new `emsdk-portable` zip and tar.gz packages. @kripken : that is done in the Buildbot dashboard by manually launching the `emsdk-win-updater`, `emsdk-osx-updater` and `emsdk-linux-updater` build tasks. Those tasks run [deploy_emsdk.py](https://github.com/juj/emslave/blob/master/bin/deploy_emsdk.py) to zip up and upload a emsdk-portables for download.

I was not able to find the link to the Buildbot dashboard in my email inbox, could you link to that here?

**Comment by k2snowman69** [comment]
Just curious: It's been a while since the documentation was changed requiring windows users to install python separately from emsdk (#6298). Is this now the official norm or still just a work around until bundling python into emsdk gets resolved? We haven't changed our CI yet to install python and don't want to put in the time if in a few weeks/months it's not going to matter.

**Comment by kripken** [comment]
There are no current plans to improve the windows SDK install and bundle things like python - I'd love for us to, but unless someone volunteers, for now the best we can do is an experience similar to the other platforms.

**Comment by Lursun** [comment]
In MacOS
$ /Applications/Python\ 2.7/Install\ Certificates.command
This is work

ref:https://stackoverflow.com/questions/27835619/urllib-and-ssl-certificate-verify-failed-error

**Comment by GeonChen** [comment]
Firstly,I typed "emsdk install latest" in git cmd，but it said "bash:git:command not found"
and then I got the issue code look like #6723  when i typed ./emsdk install latest on Windows10.
Finally,I set the system path point to emsdk dir and typed "emsdk install latest" again.
It worked !!  Silly me. By the way，my python version is 2.7.15.

**Comment by WhiteHexagon** [comment]
macos 10.12.4 following your getting_started for 1.38.28.  `./emsdk install latest` gave me the same tlsv1 error.  Following your instructions "Otherwise you can manually install and use Python 2.7.12 **or newer**"  I did a `brew install python3` however to get this working I actually needed `brew install python2` which now shows 2.7.15.

**Comment by gaopinghuang0** [comment]
`python ./emsdk install latest` works for me. I installed the newer python 2.7.16, but without typing python at the beginning, it doesn't work.

**Comment by freddiehonohan** [comment]
This worked for me (OSX huge headache)
https://stackoverflow.com/questions/42098126/mac-osx-python-ssl-sslerror-ssl-certificate-verify-failed-certificate-verify

**Comment by UZIhuhuhu** [comment]
> `python ./emsdk install latest` works for me. I installed the newer python 2.7.16, but without typing python at the beginning, it doesn't work.
> 
> MacOS 10.14.5. Installed python from python.org.

it works for me (OSX)

**Comment by navidmo** [comment]
Here is bandage (not secure as you bypass cert checks) to fix it:

edit emsdk.py 

change 
    u = urlopen(url)
to
    ncontext = ssl.SSLContext()
    u = urlopen(url, context=ncontext)

Make sure to add: 
   import ssl

**Comment by rualark** [comment]
> Here is a bandage (not secure as you bypass cert checks) to fix it:
> 
> edit emsdk.py
> 
> change
> u = urlopen(url)
> to
> ncontext = ssl.SSLContext()
> u = urlopen(url, context=ncontext)
> 
> Make sure to add:
> import ssl

This results in:
```
N:\Web\site\harmony-dev\wasm\emsdk>emsdk install latest
Traceback (most recent call last):
  File "N:\Web\site\harmony-dev\wasm\emsdk\emsdk.py", line 25, in <module>
    import ssl
  File "C:\Users\Rualark\Anaconda3\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError: DLL load failed: The specified module could not be found.
```

Tried to install ssl:
![image](https://user-images.githubusercontent.com/15198808/73094433-a127c500-3ef1-11ea-9fa1-bb69293927c1.png)
