### ISSUE TITLE
'emscripten_float64x2_add': symbol multiply defined!

### ISSUE THREAD

**Issue by Kukunin** [kripken/emscripten#5676]
I try to build a project with `emcmake`. It compiles well, but then it returns `error: Linking globals named 'emscripten_float64x2_add': symbol multiply defined!`. Because of name of the symbol I guess it's emscipten problem, not the project I try to build. 

I have emscripten installed on OSX via `brew install emscripten`. 

Here is last lines of `make -j4` command:

```
[100%] Linking CXX executable ../../bin/REGoth.html
WARNING:root:forcing separate asm output (--separate-asm), because -s PRECISE_F32=2 or -s USE_PTHREADS=2 was passed.
error: Linking globals named 'emscripten_float64x2_add': symbol multiply defined!
ERROR:root:Failed to run llvm optimizations: 
WARNING:root:Note: Input file "@/tmp/tmpb8rIJd.response" did not exist.
make[2]: *** [bin/REGoth.html] Error 1
make[1]: *** [src/target/CMakeFiles/REGoth.dir/all] Error 2
make: *** [all] Error 2
```

Here is output of `emcc -v`

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.22
clang version 4.0.0  (emscripten 1.37.22 : 1.37.22)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /usr/local/opt/emscripten/libexec/llvm/bin
INFO:root:(Emscripten: Running sanity checks)
```

`CMakeList.txt` is located here: https://github.com/REGoth-project/REGoth/blob/web-fixes-2/CMakeLists.txt. 

The project is huge, and consists of bunch of subprojects, so the surface is huge. 
I guess it's not enough information to locate the problem, but I'd happy to provide me, I just don't know what matters.

Thanks

**Comment by Kukunin** [comment]
I dag more information for you. Linux machine 1.37.22 **FAILS**

```
root@5c36be77eed1:/src/jsbuild2# emcc -v
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.22
clang version 4.0.0  (emscripten 1.37.22 : 1.37.22)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /emsdk_portable/llvm/clang/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.2
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Selected multilib: .;@m64
INFO:root:(Emscripten: Running sanity checks)
``` 

But Linux machine with 1.37.21 **WORKS** on the same codebase

```
emcc (Emscripten gcc/clang-like replacement + linker emulating GNU ld) 1.37.21
clang version 4.0.0  (emscripten 1.37.21 : 1.37.21)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /emsdk_portable/llvm/clang/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.8.4
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9.2
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/4.9
Candidate multilib: .;@m64
Selected multilib: .;@m64
INFO:root:(Emscripten: Running sanity checks)
```

So that is not related to OSX, but the problem of 1.37.22 minor version

**Comment by kripken** [comment]
Thanks for reporting. This doesn't sound like a known regression. Can you bisect between those two versions, to find the bad commit?

**Comment by kripken** [comment]
Thanks. Makes sense, that commit removed the "inline" and made it compile in C89 mode... but then it will hit those duplicate symbol errors, so we need to create a library for this.

cc @juj, perhaps you already had a plan for that? I seem to remember discussing it.

**Comment by kgritesh** [comment]
@kripken @juj i am also facing this problem. Any progress  on this.

**Comment by juj** [comment]
Thanks for reporting. Unfortunately we can't make these separate libraries, since otherwise we'd be potentially relying on LTO to inline. Fix in above PR.
