### ISSUE TITLE
executable crashes when building with 1.38.13 and using -s USE_PTHREADS=1

### ISSUE THREAD

**Issue by nickshinpho** [kripken/emscripten#7277]
i was trying to build one of our libraries and it was failing to ~compile~ run a simple test:

the test code: conftest.c

```
#include <stdio.h>
int
main ()
{
FILE *f = fopen ("conftest.out", "w");
 return ferror (f) || fclose (f) != 0;

  ;
  return 0;
}
```

[edit: when compiled, and run] this works:
```
emcc -o conftest conftest.c
./conftest
```

while this fails [Edit: to run] on 1.38.13 (but works with 1.38.11):
```
emcc -o conftest -s USE_PTHREADS=1 conftest.c
./conftest
````

**Comment by kripken** [comment]
It works for me. What error do you see?

**Comment by nickshinpho** [comment]
sorry about that -- i've corrected the details above.

but basically, working versions (i.e. running `./conftest`) just exits "normally".

but when built with 1.38.13 and using the -s USE_PTHREADS=1 switch., running `./conftest` errors and dumps a stacktrace with: `TypeError: out is not a function`

**Comment by kripken** [comment]
I see. The error message is not clear (I'll look into fixing it), but the stack trace goes through
```
assert(ENVIRONMENT_IS_WEB || ENVIRONMENT_IS_WORKER, 'Pthreads do not work in non-browser environments yet (need Web Workers, or an alternative to them)');
```
which should have been shown. It is not expected that pthreads builds work in the shell, yet. Running configure tests without pthreads should work.

**Comment by nickshinpho** [comment]
i'm building a library (ICU) which needs to be built via `emconfigure`.  (i know there's an ICU emscripten ports.  but, i am getting `missing symbols` when using it -- UnrealEngine is currently using an older version of ICU...)

is there a way to add a check/allow for when building via a `configure` (test)?

**Comment by kripken** [comment]
Some configure scripts may have options (try `./configure --help`). But emscripten would not add `USE_PTHREADS=1` by itself, so either the configure script is (if it has an emscripten code path?) or something in your setup is.

But maybe we should focus on fixing the ICU in ports, do you have a testcase showing the issue there?

**Comment by nickshinpho** [comment]
ah, i put that switch (`-s USE_PTHREADS=1`) in our builds.

but, what's interesting is that when i pulled that out, the `./configure` sequence still fails.

it seems to be linking in library_pthread_stubs.js (when not using `-s USE_PTHREADS=1`).


note: this is the only library we build via `emconfigure`.  all of our other libs built for HTML5 are done via `cmake` and none of those builds fails with `-s USE_PTHREADS=1`.  (i am trying to use emscripten ports -- but, this and a couple of more libs needs specific versions for UE4.)


here's how to repro:

UE4 uses (admittedly, an old version of) ICU:

- https://github.com/EpicGames/UnrealEngine/tree/master/Engine/Source/ThirdParty/ICU/icu4c-53_1

if you do not have access to UE4 github source yet, you can get it from here:

- http://site.icu-project.org/download/53#TOC-ICU4C-Download

i have tried building it like this:

```
cd .../icu4c-53_1
mkdir html5-build-O3-pthreads html5-build-O3-nopthreads
cd html5-build-O3-pthreads
emconfigure ../source/configure -O3 -s SIMD=0 -s USE_PTHREADS=1
```

trying without pthreads:

```
cd ../html5-build-O3-nopthreads
emconfigure ../source/configure -O3 -s SIMD=0
```

both will fail to complete running `./configure`...

**Comment by kripken** [comment]
@nickshinpho Can you get the failing testcase from the configure script? I don't have a UE4 setup on my current machine, and to debug this all I'd need is the `config.log` file, after it fails for you, probably. Otherwise I can try to find the time to set up a UE4 dev environment.

**Comment by jgravelle-google** [comment]
What output do you get for this? Is this OSX or Linux?
I tried this with emsdk's prebuilt 1.38.13 on Linux, and was able to get ICU working. I had to `dos2unix` the various configure files, and `chmod +x configure`, but then it worked.

**Comment by kripken** [comment]
Is 62 (the current version in `icu.py`) not good for you?

I don't see an example of a mixed c/c++ projects in ports. But basically `get` returns the compiled bitcode, so instead of calling `build_port` it can issue the emcc etc. commands manually, with different arguments to each file, as needed.

**Comment by nickshinpho** [comment]
ah yeah - i tried using latest ICU earlier

>  (i know there's an ICU emscripten ports. but, i am getting missing symbols when using it -- UnrealEngine is currently using an older version of ICU...)

i'll see what i can do with `get`.

**Comment by kainino0x** [comment]
fyi, seeing this on Linux as well.
